import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

/**
 * Turns a report - columns plus rows of plain values - into CSV, Excel or PDF.
 *
 * Money arrives as a Decimal-formatted string ("12345.60") and is written as
 * such: no float ever touches an amount on its way into a file.
 */

export type ColumnType = 'text' | 'number' | 'money' | 'date' | 'minutes';

export interface ReportColumn {
  key: string;
  label: string;
  type?: ColumnType;
  /** Relative width in the PDF layout. */
  width?: number;
}

export type CellValue = string | number | null;
export type ReportRow = Record<string, CellValue>;

export interface ReportDocument {
  title: string;
  subtitle: string;
  columns: ReportColumn[];
  rows: ReportRow[];
  /** Label/value pairs shown under the table (totals). */
  summary: { label: string; value: string }[];
  generatedAt: Date;
  generatedBy: string;
  companyName: string;
}

// ---------------------------------------------------------------------------
// CSV
// ---------------------------------------------------------------------------

/**
 * A text cell a spreadsheet would read as a formula (=, +, -, @, tab, CR) is
 * prefixed with an apostrophe, so an employee named "=HYPERLINK(...)" cannot
 * run anything on the machine of whoever opens the export. Numeric cells are
 * written as they are - a negative amount is data, not a formula.
 */
export function neutraliseFormula(value: string): string {
  return /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
}

function csvCell(value: CellValue, type: ColumnType): string {
  if (value === null || value === undefined) return '';
  const text = typeof value === 'number' || type === 'money' || type === 'number' || type === 'minutes'
    ? String(value)
    : neutraliseFormula(String(value));
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function toCsv(report: ReportDocument): Buffer {
  const lines = [
    report.columns.map((column) => csvCell(column.label, 'text')).join(','),
    ...report.rows.map((row) => report.columns.map((column) => csvCell(row[column.key] ?? null, column.type ?? 'text')).join(',')),
  ];
  // The byte-order mark makes Excel open UTF-8 (Arabic names) correctly.
  return Buffer.from(`﻿${lines.join('\r\n')}\r\n`, 'utf8');
}

// ---------------------------------------------------------------------------
// Excel
// ---------------------------------------------------------------------------

export async function toXlsx(report: ReportDocument): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Pollux HR';
  workbook.created = report.generatedAt;

  const sheet = workbook.addWorksheet(report.title.slice(0, 31).replace(/[\\/?*[\]:]/g, ' '), {
    views: [{ state: 'frozen', ySplit: 1 }],
  });
  sheet.columns = report.columns.map((column) => ({
    header: column.label,
    key: column.key,
    width: Math.max(10, Math.min(40, (column.width ?? 1) * 12)),
    style:
      column.type === 'money'
        ? { numFmt: '#,##0.00' }
        : column.type === 'number'
          ? { numFmt: '0.##' }
          : {},
  }));
  const header = sheet.getRow(1);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F2A44' } };

  for (const row of report.rows) {
    const values: Record<string, string | number | null> = {};
    for (const column of report.columns) {
      const value = row[column.key] ?? null;
      // Cells are typed as numbers only where the column is numeric; the
      // Decimal string is parsed at the very edge, for display in Excel.
      values[column.key] =
        value !== null && (column.type === 'money' || column.type === 'number' || column.type === 'minutes') && value !== ''
          ? Number(value)
          : value;
    }
    sheet.addRow(values);
  }
  sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: report.columns.length } };

  const info = workbook.addWorksheet('Report info');
  info.columns = [
    { header: 'Field', key: 'field', width: 22 },
    { header: 'Value', key: 'value', width: 60 },
  ];
  info.getRow(1).font = { bold: true };
  info.addRows([
    { field: 'Report', value: report.title },
    { field: 'Filters', value: report.subtitle },
    { field: 'Company', value: report.companyName },
    { field: 'Generated at', value: report.generatedAt.toISOString() },
    { field: 'Generated by', value: report.generatedBy },
    ...report.summary.map((entry) => ({ field: entry.label, value: entry.value })),
  ]);

  return Buffer.from(await workbook.xlsx.writeBuffer());
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------

const INK = '#172033';
const MUTED = '#667085';
const HEADER_FILL = '#1f2a44';
const ZEBRA = '#f4f6fa';

function formatCell(value: CellValue, type: ColumnType): string {
  if (value === null || value === undefined || value === '') return '-';
  if (type === 'money' && typeof value === 'string' && /^-?\d+(\.\d+)?$/.test(value)) {
    const negative = value.startsWith('-');
    const [whole, cents = '00'] = (negative ? value.slice(1) : value).split('.') as [string, string?];
    return `${negative ? '-' : ''}${whole.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}.${cents.padEnd(2, '0')}`;
  }
  return String(value);
}

export function toPdf(report: ReportDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
      margin: 36,
      bufferPages: true,
      info: { Title: report.title, Author: 'Pollux HR', CreationDate: report.generatedAt },
    });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = doc.page.margins.left;
    const right = doc.page.width - doc.page.margins.right;
    const width = right - left;
    const bottom = doc.page.height - doc.page.margins.bottom - 24;
    const totalWeight = report.columns.reduce((total, column) => total + (column.width ?? 1), 0);
    const widths = report.columns.map((column) => ((column.width ?? 1) / totalWeight) * width);
    const rowHeight = 16;

    const drawHeader = (y: number): number => {
      doc.rect(left, y, width, rowHeight + 2).fill(HEADER_FILL);
      let x = left;
      doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#ffffff');
      report.columns.forEach((column, index) => {
        const columnWidth = widths[index] ?? 0;
        const numeric = column.type === 'money' || column.type === 'number' || column.type === 'minutes';
        doc.text(column.label, x + 3, y + 5, { width: columnWidth - 6, align: numeric ? 'right' : 'left', lineBreak: false, ellipsis: true });
        x += columnWidth;
      });
      return y + rowHeight + 2;
    };

    // Title block
    doc.font('Helvetica-Bold').fontSize(15).fillColor(INK).text(report.title, left, 36);
    doc.font('Helvetica').fontSize(9).fillColor(MUTED).text(`${report.companyName}  ·  ${report.subtitle}`, left, 56, { width });

    let y = drawHeader(78);
    doc.font('Helvetica').fontSize(7.5);

    if (report.rows.length === 0) {
      doc.fillColor(MUTED).text('No rows match these filters.', left + 3, y + 6);
      y += rowHeight + 6;
    }

    report.rows.forEach((row, rowIndex) => {
      if (y + rowHeight > bottom) {
        doc.addPage();
        y = drawHeader(36);
        doc.font('Helvetica').fontSize(7.5);
      }
      if (rowIndex % 2 === 1) doc.rect(left, y, width, rowHeight).fill(ZEBRA);
      let x = left;
      doc.fillColor(INK);
      report.columns.forEach((column, index) => {
        const columnWidth = widths[index] ?? 0;
        const type = column.type ?? 'text';
        const numeric = type === 'money' || type === 'number' || type === 'minutes';
        doc.text(formatCell(row[column.key] ?? null, type), x + 3, y + 4.5, {
          width: columnWidth - 6,
          align: numeric ? 'right' : 'left',
          lineBreak: false,
          ellipsis: true,
        });
        x += columnWidth;
      });
      y += rowHeight;
    });

    if (report.summary.length > 0) {
      if (y + 20 + report.summary.length * 12 > bottom) {
        doc.addPage();
        y = 36;
      }
      y += 12;
      doc.font('Helvetica-Bold').fontSize(9).fillColor(INK).text('Summary', left, y);
      y += 14;
      doc.font('Helvetica').fontSize(8.5);
      for (const entry of report.summary) {
        doc.fillColor(MUTED).text(entry.label, left, y, { width: 220, lineBreak: false });
        doc.fillColor(INK).text(entry.value, left + 220, y, { width: width - 220, lineBreak: false });
        y += 12;
      }
    }

    // Footer on every page
    const range = doc.bufferedPageRange();
    for (let index = range.start; index < range.start + range.count; index += 1) {
      doc.switchToPage(index);
      const footerY = doc.page.height - doc.page.margins.bottom - 10;
      doc
        .font('Helvetica')
        .fontSize(7)
        .fillColor(MUTED)
        .text(
          `Pollux HR · generated ${report.generatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC by ${report.generatedBy} · confidential`,
          left,
          footerY,
          { width: width / 2, lineBreak: false },
        )
        .text(`Page ${index - range.start + 1} of ${range.count}`, left + width / 2, footerY, { width: width / 2, align: 'right', lineBreak: false });
    }

    doc.end();
  });
}
